import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "The team building payments, billing, and workflow infrastructure for modern African businesses.",
};

export default function Page() {
  return (
    <div id="page-about" className="page active pw">
    <section className="section" style={{paddingTop:"100px",background:"var(--p)"}}>
    <div className="inner two-col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"64px",alignItems:"center"}}>
    <div>
      <p style={{fontSize:"11px",fontWeight:"600",letterSpacing:"1.2px",textTransform:"uppercase",color:"rgba(255,255,255,0.4)",marginBottom:"16px"}}>Our story</p>
      <h1 style={{fontFamily:"var(--fd)",fontSize:"clamp(36px,4.5vw,54px)",fontWeight:"800",lineHeight:"1.07",letterSpacing:"-1.5px",color:"#fff",marginBottom:"20px"}}>Built for African<br />businesses, by<br />Africans</h1>
      <p style={{fontSize:"17px",color:"rgba(255,255,255,0.55)",lineHeight:"1.75",maxWidth:"460px",fontWeight:"300"}}>BIPRA was founded with a single conviction: African businesses deserve world-class financial infrastructure without the complexity or geographic bias of global platforms.</p>
    </div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"16px"}}>
      <div style={{background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:"16px",padding:"28px 24px",textAlign:"center"}}><div className="grad-text-warm" style={{fontFamily:"var(--fd)",fontSize:"36px",fontWeight:"800",lineHeight:"1",marginBottom:"8px",letterSpacing:"-1px"}}>2021</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.5)"}}>Founded in Johannesburg</div></div>
      <div style={{background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:"16px",padding:"28px 24px",textAlign:"center"}}><div className="grad-text-cool" style={{fontFamily:"var(--fd)",fontSize:"36px",fontWeight:"800",lineHeight:"1",marginBottom:"8px",letterSpacing:"-1px"}}>500+</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.5)"}}>Businesses on platform</div></div>
      <div style={{background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:"16px",padding:"28px 24px",textAlign:"center"}}><div className="grad-text-green" style={{fontFamily:"var(--fd)",fontSize:"36px",fontWeight:"800",lineHeight:"1",marginBottom:"8px",letterSpacing:"-1px"}}>R2B+</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.5)"}}>Processed annually</div></div>
      <div style={{background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:"16px",padding:"28px 24px",textAlign:"center"}}><div className="grad-text-warm" style={{fontFamily:"var(--fd)",fontSize:"36px",fontWeight:"800",lineHeight:"1",marginBottom:"8px",letterSpacing:"-1px"}}>4</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.5)"}}>Products in the suite</div></div>
    </div>
    </div></section>
    <section className="section"><div className="inner two-col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"64px",alignItems:"center"}}>
    <div><p className="slabel">Our mission</p><h2 className="stitle">Simplify the financial layer of African enterprise</h2><p style={{fontSize:"16px",color:"var(--muted)",lineHeight:"1.8",marginBottom:"16px"}}>We started BIPRA after watching businesses across South Africa stitch together fragmented tools — burning time, money, and data integrity in the process.</p><p style={{fontSize:"16px",color:"var(--muted)",lineHeight:"1.8"}}>BIPRA is our answer: a cohesive suite that shares a single data model, a single API surface, and a single support team.</p></div>
    <div style={{background:"var(--off)",borderRadius:"20px",padding:"40px"}}><div style={{fontFamily:"var(--fd)",fontSize:"24px",fontWeight:"800",color:"var(--p)",lineHeight:"1.2",letterSpacing:"-.5px",marginBottom:"16px"}}>“African businesses deserve tools built for them — not adapted from elsewhere.”</div><div style={{fontSize:"13px",color:"var(--muted)"}}><strong style={{color:"var(--ink)"}}>Amohelang Makgwana</strong> — CEO &amp; Co-founder, BIPRA</div></div>
    </div></section>

    <section className="section" style={{background:"linear-gradient(180deg,var(--off) 0%,#fff 100%)"}}><div className="inner">
      <p className="slabel">Our journey</p>
      <h2 className="stitle">From idea to Africa's leading <span className="grad-text">business platform</span></h2>
      <div style={{position:"relative",paddingLeft:"32px",marginTop:"40px"}}>
        <div style={{position:"absolute",left:"11px",top:"0",bottom:"0",width:"2px",background:"linear-gradient(180deg,var(--p),var(--r),var(--vb),var(--mo))",borderRadius:"2px"}}></div>
        <div style={{display:"flex",flexDirection:"column",gap:"40px"}}>
          <div style={{position:"relative"}}><div style={{position:"absolute",left:"-29px",top:"4px",width:"16px",height:"16px",borderRadius:"50%",background:"var(--p)",border:"3px solid #fff",boxShadow:"0 0 0 2px var(--p)"}}></div><div style={{fontSize:"12px",fontWeight:"700",color:"var(--p)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"6px"}}>2021 — Founded</div><div style={{fontSize:"17px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px"}}>BIPRA incorporated in Johannesburg</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"560px"}}>Founded by a team of fintech operators who had lived the problem — fragmented tools, broken workflows, and financial infrastructure not built for Africa.</p></div>
          <div style={{position:"relative"}}><div style={{position:"absolute",left:"-29px",top:"4px",width:"16px",height:"16px",borderRadius:"50%",background:"var(--r)",border:"3px solid #fff",boxShadow:"0 0 0 2px var(--r)"}}></div><div style={{fontSize:"12px",fontWeight:"700",color:"var(--r)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"6px"}}>2022 — First product</div><div style={{fontSize:"17px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px"}}>BipraPay goes live</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"560px"}}>BipraPay launched with 12 enterprise customers. First payroll run: 847 employees paid in under 90 seconds. The product thesis was validated.</p></div>
          <div style={{position:"relative"}}><div style={{position:"absolute",left:"-29px",top:"4px",width:"16px",height:"16px",borderRadius:"50%",background:"var(--r)",border:"3px solid #fff",boxShadow:"0 0 0 2px var(--r)"}}></div><div style={{fontSize:"12px",fontWeight:"700",color:"var(--r)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"6px"}}>2022 — Audit engine</div><div style={{fontSize:"17px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px"}}>BipraPay adds a built-in financial audit engine</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"560px"}}>BipraPay absorbed full financial auditing into its core — the first South African payment platform to include immutable audit trails at the infrastructure layer, in the same product as the payment itself.</p></div>
          <div style={{position:"relative"}}><div style={{position:"absolute",left:"-29px",top:"4px",width:"16px",height:"16px",borderRadius:"50%",background:"var(--vb)",border:"3px solid #fff",boxShadow:"0 0 0 2px var(--vb)"}}></div><div style={{fontSize:"12px",fontWeight:"700",color:"var(--vb)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"6px"}}>2023 — Smart metering</div><div style={{fontSize:"17px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px"}}>VeriBills: smart meter to bill in 5 minutes</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"560px"}}>VeriBills launched for utilities and municipalities. First deployment: 3,800 smart meters across 12 municipality contracts. The billing cycle dropped from 3 days to overnight.</p></div>
          <div style={{position:"relative"}}><div style={{position:"absolute",left:"-29px",top:"4px",width:"16px",height:"16px",borderRadius:"50%",background:"var(--mo)",border:"3px solid #fff",boxShadow:"0 0 0 2px var(--mo)"}}></div><div style={{fontSize:"12px",fontWeight:"700",color:"var(--mo)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"6px"}}>2024 — Enterprise</div><div style={{fontSize:"17px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px"}}>Morr ERP — the full enterprise suite</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"560px"}}>Morr ERP completed the BIPRA suite. Budgeting, HR, and digital documents — finally unified with the payments and billing products on a single data model.</p></div>
          <div style={{position:"relative"}}><div style={{position:"absolute",left:"-29px",top:"4px",width:"16px",height:"16px",borderRadius:"50%",background:"linear-gradient(135deg,var(--p),var(--r))",border:"3px solid #fff",boxShadow:"0 0 0 2px var(--p)"}}></div><div style={{fontSize:"12px",fontWeight:"700",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"6px"}} className="grad-text">2025 — Today</div><div style={{fontSize:"17px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px"}}>500+ businesses. R2B+ processed. Growing.</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"560px"}}>BIPRA is now trusted by over 500 organisations across 8 African countries — from fast-growing fintechs to government departments to enterprise conglomerates.</p></div>
        </div>
      </div>
    </div></section>
    <section className="section" style={{background:"var(--off)"}}><div className="inner">
    <p className="slabel">Our values</p><h2 className="stitle" style={{marginBottom:"48px"}}>What we stand for</h2>
    <div className="g2">
      <div className="gcard shine grid-pop tilt" style={{padding:"32px",borderRadius:"16px",display:"flex",gap:"20px",alignItems:"flex-start"}}><div style={{width:"40px",height:"40px",borderRadius:"10px",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"800",color:"var(--p)"}}>01</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"18px",fontWeight:"700",marginBottom:"8px"}}>African-first</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75"}}>We build for African businesses, on African infrastructure, with African compliance requirements in mind from day one.</p></div></div>
      <div className="gcard shine grid-pop tilt" style={{padding:"32px",borderRadius:"16px",display:"flex",gap:"20px",alignItems:"flex-start"}}><div style={{width:"40px",height:"40px",borderRadius:"10px",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"800",color:"var(--p)"}}>02</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"18px",fontWeight:"700",marginBottom:"8px"}}>Radical simplicity</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75"}}>Enterprise software should not be complicated. We obsess over reducing friction in every workflow we touch.</p></div></div>
      <div className="gcard shine grid-pop tilt" style={{padding:"32px",borderRadius:"16px",display:"flex",gap:"20px",alignItems:"flex-start"}}><div style={{width:"40px",height:"40px",borderRadius:"10px",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"800",color:"var(--p)"}}>03</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"18px",fontWeight:"700",marginBottom:"8px"}}>Trust through transparency</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75"}}>Our clients trust us with the most sensitive parts of their business. We earn that trust through honesty and reliability.</p></div></div>
      <div className="gcard shine grid-pop tilt" style={{padding:"32px",borderRadius:"16px",display:"flex",gap:"20px",alignItems:"flex-start"}}><div style={{width:"40px",height:"40px",borderRadius:"10px",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"800",color:"var(--p)"}}>04</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"18px",fontWeight:"700",marginBottom:"8px"}}>Built to scale</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75"}}>A product that works for 10 users must work equally well for 10,000. We engineer for scale from the first line of code.</p></div></div>
    </div></div></section>
    <section className="section"><div className="inner">
    <p className="slabel">The team</p><h2 className="stitle" style={{marginBottom:"48px"}}>Who's behind BIPRA</h2>
    <div className="g3">
      <div style={{display:"flex",alignItems:"center",gap:"16px",padding:"20px 24px",background:"var(--off)",borderRadius:"16px"}}><div style={{width:"52px",height:"52px",borderRadius:"50%",background:"#5533FF",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontWeight:"800",fontSize:"16px",color:"#fff"}}>AM</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"15px",fontWeight:"700",marginBottom:"2px"}}>Amohelang Makgwana</div><div style={{fontSize:"12px",color:"var(--muted)"}}>Chief Executive Officer</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:"16px",padding:"20px 24px",background:"var(--off)",borderRadius:"16px"}}><div style={{width:"52px",height:"52px",borderRadius:"50%",background:"#E8152A",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontWeight:"800",fontSize:"16px",color:"#fff"}}>ZD</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"15px",fontWeight:"700",marginBottom:"2px"}}>Zara Dlamini</div><div style={{fontSize:"12px",color:"var(--muted)"}}>Chief Technology Officer</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:"16px",padding:"20px 24px",background:"var(--off)",borderRadius:"16px"}}><div style={{width:"52px",height:"52px",borderRadius:"50%",background:"#0A7B3E",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontWeight:"800",fontSize:"16px",color:"#fff"}}>TN</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"15px",fontWeight:"700",marginBottom:"2px"}}>Thabo Nkosi</div><div style={{fontSize:"12px",color:"var(--muted)"}}>Chief Financial Officer</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:"16px",padding:"20px 24px",background:"var(--off)",borderRadius:"16px"}}><div style={{width:"52px",height:"52px",borderRadius:"50%",background:"#7B5FFF",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontWeight:"800",fontSize:"16px",color:"#fff"}}>AR</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"15px",fontWeight:"700",marginBottom:"2px"}}>Ayasha Reddy</div><div style={{fontSize:"12px",color:"var(--muted)"}}>VP Product</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:"16px",padding:"20px 24px",background:"var(--off)",borderRadius:"16px"}}><div style={{width:"52px",height:"52px",borderRadius:"50%",background:"#B45309",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontWeight:"800",fontSize:"16px",color:"#fff"}}>LO</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"15px",fontWeight:"700",marginBottom:"2px"}}>Lebo Osei</div><div style={{fontSize:"12px",color:"var(--muted)"}}>VP Engineering</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:"16px",padding:"20px 24px",background:"var(--off)",borderRadius:"16px"}}><div style={{width:"52px",height:"52px",borderRadius:"50%",background:"#3D22CC",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0"}}><span style={{fontFamily:"var(--fd)",fontWeight:"800",fontSize:"16px",color:"#fff"}}>SM</span></div><div><div style={{fontFamily:"var(--fd)",fontSize:"15px",fontWeight:"700",marginBottom:"2px"}}>Sipho Mahlangu</div><div style={{fontSize:"12px",color:"var(--muted)"}}>VP Sales</div></div></div>
    </div></div></section>
    <section className="section" style={{background:"var(--off)"}}><div className="inner">
    <p className="slabel">Where we operate</p><h2 className="stitle" style={{marginBottom:"48px"}}>Built in Africa, for Africa</h2>
    <div className="g3" style={{gap:"20px"}}>
      <div className="gcard shine grid-pop tilt" style={{borderRadius:"16px",padding:"28px"}}>
        <div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"4px"}}>Johannesburg, South Africa</div>
        <div style={{fontSize:"12px",fontWeight:"600",color:"var(--p)",textTransform:"uppercase",letterSpacing:".6px",marginBottom:"12px"}}>Headquarters</div>
        <p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.7"}}>Engineering, product, and support are based here, close to our largest customer base.</p>
      </div>
      <div className="gcard shine grid-pop tilt" style={{borderRadius:"16px",padding:"28px"}}>
        <div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"4px"}}>Nairobi, Kenya</div>
        <div style={{fontSize:"12px",fontWeight:"600",color:"var(--p)",textTransform:"uppercase",letterSpacing:".6px",marginBottom:"12px"}}>Regional hub</div>
        <p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.7"}}>Sales and partnerships covering East Africa, integrated with local banking and mobile-money rails.</p>
      </div>
      <div className="gcard shine grid-pop tilt" style={{borderRadius:"16px",padding:"28px"}}>
        <div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"4px"}}>Port Louis, Mauritius</div>
        <div style={{fontSize:"12px",fontWeight:"600",color:"var(--p)",textTransform:"uppercase",letterSpacing:".6px",marginBottom:"12px"}}>Regional hub</div>
        <p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.7"}}>Sales and partnerships for the Indian Ocean market, supporting cross-border and multi-currency clients.</p>
      </div>
    </div></div></section>
    <section style={{background:"var(--ink)",padding:"80px 5%"}}><div className="inner two-col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"64px",alignItems:"center"}}>
    <div><p style={{fontSize:"11px",fontWeight:"600",letterSpacing:"1.2px",textTransform:"uppercase",color:"rgba(255,255,255,0.35)",marginBottom:"16px"}}>Careers</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(28px,3vw,38px)",fontWeight:"800",color:"#fff",letterSpacing:"-.8px",marginBottom:"16px",lineHeight:"1.1"}}>Help us build the financial backbone of Africa</h2><p style={{fontSize:"16px",color:"rgba(255,255,255,0.4)",lineHeight:"1.75",marginBottom:"32px"}}>We're growing fast and always looking for exceptional people who care about the problem as much as the craft.</p><Link className="btn btn-w btn-lg" href="/careers">View open roles</Link></div>
    <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>
      <Link href="/careers" style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",background:"rgba(255,255,255,0.05)",borderRadius:"10px",border:"1px solid rgba(255,255,255,0.06)",textDecoration:"none"}}><span style={{fontSize:"14px",fontWeight:"500",color:"#fff"}}>Engineering</span><span style={{fontSize:"11px",padding:"3px 10px",borderRadius:"100px",background:"rgba(85,51,255,0.3)",color:"#A89EFF"}}>Hiring</span></Link>
      <Link href="/careers" style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",background:"rgba(255,255,255,0.05)",borderRadius:"10px",border:"1px solid rgba(255,255,255,0.06)",textDecoration:"none"}}><span style={{fontSize:"14px",fontWeight:"500",color:"#fff"}}>Product &amp; Design</span><span style={{fontSize:"11px",padding:"3px 10px",borderRadius:"100px",background:"rgba(85,51,255,0.3)",color:"#A89EFF"}}>Hiring</span></Link>
      <Link href="/careers" style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",background:"rgba(255,255,255,0.05)",borderRadius:"10px",border:"1px solid rgba(255,255,255,0.06)",textDecoration:"none"}}><span style={{fontSize:"14px",fontWeight:"500",color:"#fff"}}>Sales &amp; Partnerships</span><span style={{fontSize:"11px",padding:"3px 10px",borderRadius:"100px",background:"rgba(85,51,255,0.3)",color:"#A89EFF"}}>Hiring</span></Link>
      <Link href="/careers" style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",background:"rgba(255,255,255,0.05)",borderRadius:"10px",border:"1px solid rgba(255,255,255,0.06)",textDecoration:"none"}}><span style={{fontSize:"14px",fontWeight:"500",color:"#fff"}}>Customer Success</span><span style={{fontSize:"11px",padding:"3px 10px",borderRadius:"100px",background:"rgba(85,51,255,0.3)",color:"#A89EFF"}}>Hiring</span></Link>
    </div></div></section>
    </div>
  );
}
