import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BipraPay",
  description: "Instant payment gateway with sub-second processing for payroll, bulk disbursements, and supplier payments.",
};

export default function Page() {
  return (
    <div id="page-biprapay" className="page active pw">
    <section className="section" style={{paddingTop:"100px",background:"linear-gradient(135deg,#FFF5F5 0%,#fff 60%)"}}>
    <div className="inner two-col" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"64px",alignItems:"center"}}>
    <div>
      <div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"20px"}}><div style={{width:"48px",height:"48px",borderRadius:"13px",background:"var(--rl)",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#E8152A" strokeWidth="2"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"></path></svg></div><span style={{fontFamily:"var(--fd)",fontWeight:"700",fontSize:"15px",color:"var(--r)"}}>BipraPay</span></div>
      <h1 style={{fontFamily:"var(--fd)",fontSize:"clamp(36px,4.5vw,54px)",fontWeight:"800",lineHeight:"1.07",letterSpacing:"-1.5px",marginBottom:"20px"}}>Payments at the<br /><span className="grad-text-warm">speed of now</span></h1>
      <p style={{fontSize:"17px",color:"var(--muted)",lineHeight:"1.75",maxWidth:"460px",marginBottom:"36px",fontWeight:"300"}}>Instant payment processing for businesses where every millisecond counts — e-commerce, payroll, mass disbursements.</p>
      <div style={{display:"flex",gap:"16px",flexWrap:"wrap"}}><Link className="btn btn-r btn-lg" href="/contact">Get started</Link><Link className="btn btn-o btn-lg" href="/pricing">View pricing</Link></div>
    </div>
    <div style={{background:"var(--ink)",borderRadius:"20px",padding:"32px",textAlign:"center",boxShadow:"var(--sh)"}}>
      <div style={{fontSize:"12px",color:"rgba(255,255,255,0.4)",textTransform:"uppercase",letterSpacing:"1px",marginBottom:"24px"}}>Average processing time</div>
      <div style={{fontFamily:"var(--fd)",fontSize:"80px",fontWeight:"800",color:"var(--r)",letterSpacing:"-3px",lineHeight:"1"}}>&lt;800<span style={{fontSize:"28px",color:"rgba(255,255,255,0.5)",letterSpacing:"0"}}>ms</span></div>
      <div style={{height:"2px",background:"rgba(255,255,255,0.06)",borderRadius:"2px",margin:"28px 0",position:"relative"}}><div style={{position:"absolute",left:"0",top:"-6px",width:"68%",height:"14px",borderRadius:"7px",background:"var(--r)",opacity:".9"}}></div></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"16px"}}>
        <div><div style={{fontFamily:"var(--fd)",fontSize:"20px",fontWeight:"700",color:"#fff",lineHeight:"1",marginBottom:"4px"}}>R12.4M</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>Processed today</div></div>
        <div><div style={{fontFamily:"var(--fd)",fontSize:"20px",fontWeight:"700",color:"#fff",lineHeight:"1",marginBottom:"4px"}}>99.97%</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>Success rate</div></div>
        <div><div style={{fontFamily:"var(--fd)",fontSize:"20px",fontWeight:"700",color:"#fff",lineHeight:"1",marginBottom:"4px"}}>247</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>TPS capacity</div></div>
      </div>
    </div>
    </div></section>


    <section style={{background:"linear-gradient(135deg,#13091e 0%,#0D0B1E 45%,#1f0a14 100%)",padding:"110px 5%",position:"relative",overflow:"hidden"}}>
      <div className="blob-drift" style={{position:"absolute",top:"-120px",right:"-80px",width:"480px",height:"480px",borderRadius:"50%",background:"radial-gradient(circle,rgba(232,21,42,0.18) 0%,transparent 70%)",pointerEvents:"none"}}></div>
      <div className="blob-drift" style={{position:"absolute",bottom:"-140px",left:"-100px",width:"520px",height:"520px",borderRadius:"50%",background:"radial-gradient(circle,rgba(255,107,53,0.12) 0%,transparent 70%)",pointerEvents:"none",animationDelay:"4s"}}></div>
      <div className="inner" style={{position:"relative",zIndex:"1"}}>
        <div style={{textAlign:"center",marginBottom:"70px"}}>
          <span className="band-eyebrow cine-reveal" style={{color:"#FF6B6B"}}>Watch a payment move</span>
          <h2 className="cine-reveal s1" style={{fontFamily:"'Helvetica Neue',Arial,sans-serif",fontSize:"clamp(30px,4vw,48px)",fontWeight:"800",letterSpacing:"-1.2px",color:"#fff",margin:"18px 0 14px",lineHeight:"1.08"}}>748 milliseconds.<br /><span className="grad-text-warm">Start to settled.</span></h2>
          <p className="cine-reveal s2" style={{fontSize:"16px",color:"rgba(255,255,255,0.45)",maxWidth:"520px",margin:"0 auto",lineHeight:"1.75"}}>This is the actual journey of every BipraPay transaction — replayed live, at real proportional speed.</p>
        </div>
        
        <div style={{position:"relative",maxWidth:"980px",margin:"0 auto"}}>
          
          <div className="streak" style={{top:"18%",left:"0",width:"140px",animationDelay:"0s"}}></div>
          <div className="streak" style={{top:"42%",left:"0",width:"90px",animationDelay:".7s"}}></div>
          <div className="streak" style={{top:"74%",left:"0",width:"120px",animationDelay:"1.4s"}}></div>
          
          <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"16px",position:"relative"}}>
            
            <div style={{position:"absolute",top:"32px",left:"12%",right:"12%",height:"2px",background:"rgba(255,255,255,0.08)",zIndex:"1"}}>
              <div className="packet" style={{background:"#E8152A",boxShadow:"0 0 14px rgba(232,21,42,0.9)"}}></div>
              <div className="packet d1" style={{background:"#FF6B35",boxShadow:"0 0 14px rgba(255,107,53,0.9)"}}></div>
              <div className="packet d2" style={{background:"#FCD34D",boxShadow:"0 0 14px rgba(252,211,77,0.8)"}}></div>
            </div>
    <div className="cine-reveal" style={{textAlign:"center",position:"relative",zIndex:"2"}}><div className="node-glow-r cine-reveal s1" style={{width:"64px",height:"64px",borderRadius:"18px",background:"#16112e",border:"1px solid #E8152A40",margin:"0 auto 12px",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#E8152A" strokeWidth="2"><polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline></svg></div><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"3px"}}>API call received</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>12ms · validated</div></div><div className="cine-reveal" style={{textAlign:"center",position:"relative",zIndex:"2"}}><div className="node-glow-r cine-reveal s2" style={{width:"64px",height:"64px",borderRadius:"18px",background:"#16112e",border:"1px solid #E8152A40",margin:"0 auto 12px",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#E8152A" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><polyline points="9 12 11 14 15 10"></polyline></svg></div><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"3px"}}>Compliance screen</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>48ms · AML cleared</div></div><div className="cine-reveal" style={{textAlign:"center",position:"relative",zIndex:"2"}}><div className="node-glow-r cine-reveal s3" style={{width:"64px",height:"64px",borderRadius:"18px",background:"#16112e",border:"1px solid #E8152A40",margin:"0 auto 12px",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#E8152A" strokeWidth="2"><circle cx="6" cy="19" r="3"></circle><circle cx="18" cy="5" r="3"></circle><path d="M12 19h4.5a3.5 3.5 0 0 0 0-7h-9a3.5 3.5 0 0 1 0-7H12"></path></svg></div><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"3px"}}>Rail selected</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>8ms · fastest route</div></div><div className="cine-reveal" style={{textAlign:"center",position:"relative",zIndex:"2"}}><div className="node-glow-g cine-reveal s4" style={{width:"64px",height:"64px",borderRadius:"18px",background:"#16112e",border:"1px solid #4ADE8040",margin:"0 auto 12px",display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#4ADE80" strokeWidth="2"><polyline points="20 6 9 17 4 12"></polyline></svg></div><div style={{fontSize:"13px",fontWeight:"700",color:"#fff",marginBottom:"3px"}}>Bank settled</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.4)"}}>680ms · funds cleared</div></div>      </div>
          
          <div className="cine-reveal s5" style={{marginTop:"56px",background:"rgba(255,255,255,0.04)",border:"1px solid rgba(255,255,255,0.07)",borderRadius:"16px",padding:"22px 28px",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:"16px"}}>
            <div style={{display:"flex",gap:"36px",flexWrap:"wrap"}}>
              <div><div style={{fontSize:"24px",fontWeight:"800",fontFamily:"'Helvetica Neue',Arial,sans-serif",letterSpacing:"-1px"}} className="grad-text-warm">748ms</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.35)",marginTop:"2px"}}>BipraPay average</div></div>
              <div><div style={{fontSize:"24px",fontWeight:"800",fontFamily:"'Helvetica Neue',Arial,sans-serif",letterSpacing:"-1px",color:"rgba(255,255,255,0.35)"}}>2,200ms</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.25)",marginTop:"2px"}}>Industry average</div></div>
              <div><div style={{fontSize:"24px",fontWeight:"800",fontFamily:"'Helvetica Neue',Arial,sans-serif",letterSpacing:"-1px",color:"#4ADE80"}}>3×</div><div style={{fontSize:"11px",color:"rgba(255,255,255,0.35)",marginTop:"2px"}}>Faster than the market</div></div>
            </div>
            <Link className="btn btn-r btn-md" style={{background:"linear-gradient(135deg,#FF6B35,#E8152A)",border:"none"}} href="/contact">Run your first payment</Link>
          </div>
        </div>
      </div>
    </section>
    <section className="section" style={{background:"var(--off)"}}><div className="inner"><p className="slabel">Use cases</p><h2 className="stitle">Built for every payment scenario</h2><p className="ssub">From one-off charges to millions of disbursements.</p>
    <div className="g3"><div className="card"><span className="badge b-r" style={{marginBottom:"12px"}}>Payroll</span><div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>Payroll disbursement</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.7"}}>Pay all employees in a single API call. EFT, real-time clearing, and mobile wallets.</p></div><div className="card"><span className="badge b-r" style={{marginBottom:"12px"}}>E-commerce</span><div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>E-commerce checkout</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.7"}}>Embed in any web or mobile checkout flow with pre-built UI or headless API.</p></div><div className="card"><span className="badge b-r" style={{marginBottom:"12px"}}>B2B</span><div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>Supplier payments</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.7"}}>Automate accounts payable — schedule, batch, and disburse invoices programmatically.</p></div><div className="card"><span className="badge b-r" style={{marginBottom:"12px"}}>Insurance</span><div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>Insurance payouts</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.7"}}>Trigger claims payments instantly upon approval. Days reduced to seconds.</p></div><div className="card"><span className="badge b-r" style={{marginBottom:"12px"}}>Commissions</span><div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>Commission payments</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.7"}}>Pay agents and contractors accurately on any schedule with a full audit trail.</p></div><div className="card"><span className="badge b-r" style={{marginBottom:"12px"}}>Government</span><div style={{fontFamily:"var(--fd)",fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>Government grants</div><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.7"}}>Mass disbursements to citizen beneficiaries with identity verification built in.</p></div></div>
    </div></section>

    <section className="section"><div className="inner">
      <p className="slabel">The BipraPay difference</p>
      <h2 className="stitle">How we hit sub-800ms in South Africa</h2>
      <p className="ssub">Speed is an architecture decision. Here's ours.</p>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"56px",alignItems:"start"}} className="two-col">
        <div style={{display:"flex",flexDirection:"column",gap:"16px"}}>
          <div style={{padding:"20px 24px",background:"var(--off)",borderRadius:"14px",borderLeft:"4px solid var(--r)"}}><div style={{fontSize:"14px",fontWeight:"700",color:"var(--ink)",marginBottom:"4px"}}>Edge processing nodes</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65"}}>Co-located with South African bank clearing infrastructure, eliminating cross-continental latency.</p></div>
          <div style={{padding:"20px 24px",background:"var(--off)",borderRadius:"14px",borderLeft:"4px solid var(--r)"}}><div style={{fontSize:"14px",fontWeight:"700",color:"var(--ink)",marginBottom:"4px"}}>Pre-authorisation queuing</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65"}}>Bulk payrolls of 50,000 start clearing before the batch is fully submitted.</p></div>
          <div style={{padding:"20px 24px",background:"var(--off)",borderRadius:"14px",borderLeft:"4px solid var(--r)"}}><div style={{fontSize:"14px",fontWeight:"700",color:"var(--ink)",marginBottom:"4px"}}>Intelligent rail selection</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65"}}>Our router picks the fastest available rail in real time. RTC congested? EFT same-day kicks in automatically.</p></div>
          <div style={{padding:"20px 24px",background:"var(--off)",borderRadius:"14px",borderLeft:"4px solid var(--r)"}}><div style={{fontSize:"14px",fontWeight:"700",color:"var(--ink)",marginBottom:"4px"}}>Automatic retry with backoff</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65"}}>Failed payments retry up to 3 times with exponential backoff. No manual intervention required.</p></div>
        </div>
        <div>
          <div style={{background:"var(--ink)",borderRadius:"16px",padding:"28px",marginBottom:"16px"}}>
            <div style={{fontSize:"11px",fontWeight:"600",color:"rgba(255,255,255,0.35)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"16px"}}>Response time breakdown</div>
            <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>
              <div><div style={{display:"flex",justifyContent:"space-between",marginBottom:"5px"}}><span style={{fontSize:"12px",color:"rgba(255,255,255,0.6)"}}>API validation</span><span style={{fontSize:"12px",color:"#fff"}}>12ms</span></div><div style={{height:"8px",background:"rgba(255,255,255,0.08)",borderRadius:"4px"}}><div style={{height:"100%",width:"3%",borderRadius:"4px",background:"var(--r)"}}></div></div></div>
              <div><div style={{display:"flex",justifyContent:"space-between",marginBottom:"5px"}}><span style={{fontSize:"12px",color:"rgba(255,255,255,0.6)"}}>Compliance screening</span><span style={{fontSize:"12px",color:"#fff"}}>48ms</span></div><div style={{height:"8px",background:"rgba(255,255,255,0.08)",borderRadius:"4px"}}><div style={{height:"100%",width:"14%",borderRadius:"4px",background:"var(--r)"}}></div></div></div>
              <div><div style={{display:"flex",justifyContent:"space-between",marginBottom:"5px"}}><span style={{fontSize:"12px",color:"rgba(255,255,255,0.6)"}}>Rail routing</span><span style={{fontSize:"12px",color:"#fff"}}>8ms</span></div><div style={{height:"8px",background:"rgba(255,255,255,0.08)",borderRadius:"4px"}}><div style={{height:"100%",width:"2%",borderRadius:"4px",background:"var(--r)"}}></div></div></div>
              <div><div style={{display:"flex",justifyContent:"space-between",marginBottom:"5px"}}><span style={{fontSize:"12px",color:"rgba(255,255,255,0.6)"}}>Bank clearing</span><span style={{fontSize:"12px",color:"#fff"}}>680ms</span></div><div style={{height:"8px",background:"rgba(255,255,255,0.08)",borderRadius:"4px"}}><div style={{height:"100%",width:"85%",borderRadius:"4px",background:"rgba(232,21,42,0.5)"}}></div></div></div>
              <div style={{borderTop:"1px solid rgba(255,255,255,0.08)",paddingTop:"10px",display:"flex",justifyContent:"space-between"}}><span style={{fontSize:"12px",fontWeight:"700",color:"rgba(255,255,255,0.8)"}}>Total</span><span style={{fontSize:"14px",fontWeight:"800",color:"var(--r)"}}>748ms avg</span></div>
            </div>
          </div>
          <div style={{background:"var(--rl)",borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"600",color:"var(--r)",marginBottom:"4px"}}>Industry benchmark</div><div style={{fontSize:"12px",color:"var(--r)",opacity:".75"}}>Average SA payment gateway: 2,200ms</div><div style={{fontSize:"22px",fontWeight:"800",color:"var(--r)",marginTop:"8px"}}>BipraPay is 3× faster</div></div>
        </div>
      </div>
    </div></section>

    <section className="section" style={{background:"var(--off)"}}><div className="inner">
      <p className="slabel">Disbursement types</p>
      <h2 className="stitle">Every way you need to pay</h2>
      <div className="g3" style={{gap:"20px"}}>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"14px",padding:"24px"}}><div style={{fontSize:"15px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px",display:"flex",alignItems:"center",gap:"8px"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"></path></svg>Payroll</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65",marginBottom:"12px"}}>50,000 employees paid in under 90 seconds. Multiple banks, currencies, and pay schedules.</p><div style={{fontSize:"12px",fontWeight:"600",color:"var(--r)"}}>Max: 50,000 recipients/batch</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"14px",padding:"24px"}}><div style={{fontSize:"15px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px",display:"flex",alignItems:"center",gap:"8px"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path></svg>Supplier payments</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65",marginBottom:"12px"}}>Automate accounts payable. Trigger via API when PO approval is complete.</p><div style={{fontSize:"12px",fontWeight:"600",color:"var(--r)"}}>Supports: EFT, RTC, SWIFT</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"14px",padding:"24px"}}><div style={{fontSize:"15px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px",display:"flex",alignItems:"center",gap:"8px"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>Commissions</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65",marginBottom:"12px"}}>Agent and reseller commissions calculated and paid on configurable schedules.</p><div style={{fontSize:"12px",fontWeight:"600",color:"var(--r)"}}>Daily, weekly, or monthly</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"14px",padding:"24px"}}><div style={{fontSize:"15px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px",display:"flex",alignItems:"center",gap:"8px"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>Insurance claims</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65",marginBottom:"12px"}}>Trigger payouts the moment a claim is approved. Zero manual processing steps.</p><div style={{fontSize:"12px",fontWeight:"600",color:"var(--r)"}}>Trigger: API webhook or event</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"14px",padding:"24px"}}><div style={{fontSize:"15px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px",display:"flex",alignItems:"center",gap:"8px"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"></path><rect x="9" y="3" width="6" height="4" rx="1"></rect><line x1="9" y1="12" x2="15" y2="12"></line><line x1="9" y1="16" x2="13" y2="16"></line></svg>Government grants</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65",marginBottom:"12px"}}>Mass disbursements with identity verification and POPIA-compliant data handling built in.</p><div style={{fontSize:"12px",fontWeight:"600",color:"var(--r)"}}>Compliant: POPIA, FICA, NPA</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"14px",padding:"24px"}}><div style={{fontSize:"15px",fontWeight:"700",color:"var(--ink)",marginBottom:"6px",display:"flex",alignItems:"center",gap:"8px"}}><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>E-commerce</div><p style={{fontSize:"13px",color:"var(--muted)",lineHeight:"1.65",marginBottom:"12px"}}>Accept payments and split to sellers in a single API call. Instant settlement available.</p><div style={{fontSize:"12px",fontWeight:"600",color:"var(--r)"}}>Split payments supported</div></div>
      </div>
    </div></section>

    <section className="section"><div className="inner-n"><div className="quote-block">
      <p style={{fontSize:"20px",fontWeight:"600",color:"#fff",lineHeight:"1.5",marginBottom:"24px",position:"relative",zIndex:"1"}}>"BipraPay processes our entire payroll — 800 staff across 6 provinces — in under 90 seconds. Every Friday. Without fail. The old system took 4 hours and still had errors."</p>
      <div style={{display:"flex",alignItems:"center",gap:"14px",position:"relative",zIndex:"1"}}>
        <div style={{width:"44px",height:"44px",borderRadius:"50%",background:"var(--r)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:"700",color:"#fff",flexShrink:"0"}}>ZK</div>
        <div><div style={{fontSize:"14px",fontWeight:"600",color:"#fff"}}>Zola Khumalo</div><div style={{fontSize:"12px",color:"rgba(255,255,255,0.45)"}}>Head of Finance, Ubuntu Logistics</div></div>
      </div>
    </div></div></section>
    <section style={{background:"var(--r)",padding:"80px 5%",textAlign:"center"}}><div className="inner-n"><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(26px,3vw,38px)",fontWeight:"800",color:"#fff",letterSpacing:"-.8px",marginBottom:"16px"}}>Ready to move at the speed of now?</h2><p style={{fontSize:"16px",color:"rgba(255,255,255,0.6)",marginBottom:"36px"}}>Set up BipraPay in your environment today.</p><div style={{display:"flex",gap:"16px",justifyContent:"center",flexWrap:"wrap"}}><Link className="btn btn-w btn-lg" href="/contact">Book a demo</Link><Link className="btn btn-ow btn-lg" href="/pricing">See pricing</Link></div></div></section>
    </div>
  );
}
