import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Solutions",
  description: "Industry solutions for municipalities, utilities, insurers, hospitality, and enterprise.",
};

export default function Page() {
  return (
    <div id="page-solutions" className="page active pw">
    <section className="section" style={{paddingTop:"100px",background:"linear-gradient(135deg,var(--px) 0%,#fff 60%)"}}>
      <div className="inner-n" style={{textAlign:"center"}}>
        <p className="slabel" style={{textAlign:"center"}}>Solutions</p>
        <h1 style={{fontFamily:"'Helvetica Neue',Arial,sans-serif",fontSize:"clamp(36px,5vw,56px)",fontWeight:"800",letterSpacing:"-1.5px",marginBottom:"16px",lineHeight:"1.08"}}>Built for <span className="grad-text">your industry</span></h1>
        <p style={{fontSize:"17px",color:"var(--muted)",lineHeight:"1.75",marginBottom:"0",fontWeight:"300"}}>BIPRA adapts to the specific compliance, workflow, and payment needs of your sector.</p>
      </div>
    </section>
    <section className="section"><div className="inner">
      <div style={{display:"flex",flexDirection:"column",gap:"32px"}}>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"56px",alignItems:"center",background:"#fff",borderRadius:"20px",border:"1px solid var(--border)",padding:"48px"}} className="two-col">
          <div><span className="badge b-p" style={{marginBottom:"16px"}}>Financial Services</span><h2 style={{fontSize:"28px",fontWeight:"800",letterSpacing:"-.5px",marginBottom:"14px",lineHeight:"1.2"}}>Banks, fintechs &amp; lenders</h2><p style={{fontSize:"15px",color:"var(--muted)",lineHeight:"1.75",marginBottom:"20px"}}>From payment processing to audit-ready financial reporting, BIPRA gives financial institutions a compliant, scalable infrastructure layer.</p><ul className="flist"><li className="fitem"><span className="fcheck"><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>SARB-compliant payment rails</li><li className="fitem"><span className="fcheck"><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Real-time AML transaction screening</li><li className="fitem"><span className="fcheck"><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>IFRS 9 provisioning reports</li><li className="fitem"><span className="fcheck"><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Multi-currency nostro management</li></ul><Link className="btn btn-p btn-lg" style={{marginTop:"24px"}} href="/contact">Talk to us</Link></div>
          <div style={{background:"var(--off)",borderRadius:"14px",padding:"28px"}}><div style={{fontSize:"11px",fontWeight:"600",color:"var(--muted)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"16px"}}>Products used</div><div style={{display:"flex",flexWrap:"wrap",gap:"8px"}}><span className="badge b-p">xPayments</span><span className="badge b-r">SwiftPay</span><span className="badge b-g">xBilling</span></div><div style={{height:"1px",background:"var(--border)",margin:"20px 0"}}></div><div style={{fontSize:"13px",color:"var(--muted)",marginBottom:"12px"}}>Typical deployment</div><div style={{fontSize:"24px",fontWeight:"800",color:"var(--ink)"}}>3–5 days</div></div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"56px",alignItems:"center",background:"#fff",borderRadius:"20px",border:"1px solid var(--border)",padding:"48px"}} className="two-col">
          <div style={{background:"var(--off)",borderRadius:"14px",padding:"28px"}}><div style={{fontSize:"11px",fontWeight:"600",color:"var(--muted)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"16px"}}>Products used</div><div style={{display:"flex",flexWrap:"wrap",gap:"8px"}}><span className="badge b-p">NexCore ERP</span><span className="badge b-g">xBilling</span></div><div style={{height:"1px",background:"var(--border)",margin:"20px 0"}}></div><div style={{fontSize:"13px",color:"var(--muted)",marginBottom:"12px"}}>Typical deployment</div><div style={{fontSize:"24px",fontWeight:"800",color:"var(--ink)"}}>5–7 days</div></div>
          <div><span className="badge b-g" style={{marginBottom:"16px"}}>Government &amp; Public Sector</span><h2 style={{fontSize:"28px",fontWeight:"800",letterSpacing:"-.5px",marginBottom:"14px",lineHeight:"1.2"}}>Departments &amp; municipalities</h2><p style={{fontSize:"15px",color:"var(--muted)",lineHeight:"1.75",marginBottom:"20px"}}>Manage budgets across departments, process citizen payments, and maintain compliance with PFMA and MFMA requirements.</p><ul className="flist"><li className="fitem"><span className="fcheck" style={{background:"var(--gl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#0A7B3E" strokeWidth="1.8"></polyline></svg></span>PFMA / MFMA budget compliance</li><li className="fitem"><span className="fcheck" style={{background:"var(--gl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#0A7B3E" strokeWidth="1.8"></polyline></svg></span>Auditor-General export formats</li><li className="fitem"><span className="fcheck" style={{background:"var(--gl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#0A7B3E" strokeWidth="1.8"></polyline></svg></span>Grant disbursement to beneficiaries</li><li className="fitem"><span className="fcheck" style={{background:"var(--gl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#0A7B3E" strokeWidth="1.8"></polyline></svg></span>Digital document management</li></ul><Link className="btn btn-g btn-lg" style={{marginTop:"24px"}} href="/contact">Talk to us</Link></div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"56px",alignItems:"center",background:"#fff",borderRadius:"20px",border:"1px solid var(--border)",padding:"48px"}} className="two-col">
          <div><span className="badge b-r" style={{marginBottom:"16px"}}>Retail &amp; E-commerce</span><h2 style={{fontSize:"28px",fontWeight:"800",letterSpacing:"-.5px",marginBottom:"14px",lineHeight:"1.2"}}>Online &amp; omnichannel retailers</h2><p style={{fontSize:"15px",color:"var(--muted)",lineHeight:"1.75",marginBottom:"20px"}}>Accept payments at speed, automate supplier invoice processing, and close month-end in a single day with integrated billing and reconciliation.</p><ul className="flist"><li className="fitem"><span className="fcheck" style={{background:"var(--rl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#E8152A" strokeWidth="1.8"></polyline></svg></span>Instant checkout via SwiftPay</li><li className="fitem"><span className="fcheck" style={{background:"var(--rl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#E8152A" strokeWidth="1.8"></polyline></svg></span>Automated supplier payments</li><li className="fitem"><span className="fcheck" style={{background:"var(--rl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#E8152A" strokeWidth="1.8"></polyline></svg></span>Commission &amp; affiliate payouts</li><li className="fitem"><span className="fcheck" style={{background:"var(--rl)"}}><svg width="10" height="10" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#E8152A" strokeWidth="1.8"></polyline></svg></span>Real-time revenue reconciliation</li></ul><Link className="btn btn-r btn-lg" style={{marginTop:"24px"}} href="/contact">Talk to us</Link></div>
          <div style={{background:"var(--off)",borderRadius:"14px",padding:"28px"}}><div style={{fontSize:"11px",fontWeight:"600",color:"var(--muted)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"16px"}}>Products used</div><div style={{display:"flex",flexWrap:"wrap",gap:"8px"}}><span className="badge b-r">SwiftPay</span><span className="badge b-g">xBilling</span></div><div style={{height:"1px",background:"var(--border)",margin:"20px 0"}}></div><div style={{fontSize:"13px",color:"var(--muted)",marginBottom:"12px"}}>Typical deployment</div><div style={{fontSize:"24px",fontWeight:"800",color:"var(--ink)"}}>1–2 days</div></div>
        </div>
      </div>
    </div></section>


    <section className="section" style={{background:"var(--off)"}}><div className="inner">
      <p className="slabel" style={{textAlign:"center"}}>Integrations</p>
      <h2 className="stitle" style={{textAlign:"center",maxWidth:"500px",margin:"0 auto 48px"}}>Connects with the tools you already use</h2>
      <div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:"16px"}} id="integrations-grid">
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"700",color:"var(--ink)"}}>Xero</div><div style={{fontSize:"11px",color:"var(--muted)",marginTop:"2px"}}>Accounting</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"700",color:"var(--ink)"}}>Sage</div><div style={{fontSize:"11px",color:"var(--muted)",marginTop:"2px"}}>ERP</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"700",color:"var(--ink)"}}>Salesforce</div><div style={{fontSize:"11px",color:"var(--muted)",marginTop:"2px"}}>CRM</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"700",color:"var(--ink)"}}>SAP</div><div style={{fontSize:"11px",color:"var(--muted)",marginTop:"2px"}}>Enterprise</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"700",color:"var(--ink)"}}>Slack</div><div style={{fontSize:"11px",color:"var(--muted)",marginTop:"2px"}}>Notifications</div></div>
        <div className="gcard shine grid-pop tilt" style={{borderRadius:"12px",padding:"20px",textAlign:"center"}}><div style={{fontSize:"13px",fontWeight:"700",color:"var(--ink)"}}>Zapier</div><div style={{fontSize:"11px",color:"var(--muted)",marginTop:"2px"}}>Automation</div></div>
      </div>
      <p style={{textAlign:"center",fontSize:"13px",color:"var(--muted)",marginTop:"20px"}}>+ REST API for custom integrations with any system</p>
    </div></section>
    <section style={{background:"var(--ink)",padding:"80px 5%",textAlign:"center"}}><div className="inner-n"><h2 style={{fontFamily:"'Helvetica Neue',Arial,sans-serif",fontSize:"clamp(26px,3vw,38px)",fontWeight:"800",color:"#fff",letterSpacing:"-.8px",marginBottom:"16px"}}>Find the right solution for your business</h2><p style={{fontSize:"16px",color:"rgba(255,255,255,0.4)",marginBottom:"36px"}}>Our team will map BIPRA to your exact industry requirements.</p><div style={{display:"flex",gap:"16px",justifyContent:"center",flexWrap:"wrap"}}><Link className="btn btn-w btn-lg" href="/contact">Book a consultation</Link><Link className="btn btn-ow btn-lg" href="/pricing">View pricing</Link></div></div></section>
    </div>
  );
}
