"use client";

import Link from "next/link";
import { useState } from "react";

const PRICES = {
  starter: { monthly: 2499, annual: 1999 },
  business: { monthly: 7999, annual: 6399 },
};

export default function PricingClient() {
  const [mode, setMode] = useState<"monthly" | "annual">("annual");

  return (
    <div id="page-pricing" className="page active pw">
    <section className="section" style={{paddingTop:"100px",textAlign:"center"}}><div className="inner-n">
      <p className="slabel" style={{textAlign:"center"}}>Pricing</p>
      <h1 style={{fontFamily:"var(--fd)",fontSize:"clamp(36px,5vw,56px)",fontWeight:"800",letterSpacing:"-1.5px",marginBottom:"16px",lineHeight:"1.08"}}>Transparent pricing,<br /><span className="grad-text">no surprises</span></h1>
      <p style={{fontSize:"17px",color:"var(--muted)",lineHeight:"1.75",marginBottom:"20px",fontWeight:"300"}}>Start with the products you need. Scale to the full platform as you grow.</p>
      <p style={{fontSize:"13px",color:"var(--muted)",marginBottom:"36px"}}>Looking for BipraPay's transaction fees? <Link href="/biprapay" style={{color:"var(--r)",fontWeight:"600"}}>See BipraPay pricing →</Link></p>
      <div className="toggle-wrap">
        <button className={`toggle-btn${mode === "monthly" ? " active" : ""}`} id="toggle-monthly" onClick={() => setMode("monthly")}>Monthly</button>
        <button className={`toggle-btn${mode === "annual" ? " active" : ""}`} id="toggle-annual" onClick={() => setMode("annual")}>Annual <span style={{fontSize:"10px",fontWeight:"600",padding:"2px 8px",borderRadius:"100px",background:"var(--gl)",color:"var(--g)",marginLeft:"4px"}}>Save 20%</span></button>
      </div>
    </div></section>
    <section style={{padding:"0 5% 88px"}}><div className="inner"><div className="g3" style={{alignItems:"stretch"}}>
      <div className="gcard-deep shine grid-pop tilt" style={{borderRadius:"20px",padding:"36px 32px",display:"flex",flexDirection:"column"}}>
        <div style={{fontFamily:"var(--fd)",fontSize:"22px",fontWeight:"700",marginBottom:"4px"}}>Starter</div>
        <div style={{fontSize:"13px",color:"var(--muted)",marginBottom:"28px"}}>For growing businesses</div>
        <div style={{marginBottom:"28px"}}><span style={{fontFamily:"var(--fd)",fontSize:"13px",fontWeight:"600",color:"var(--muted)",verticalAlign:"top",lineHeight:"52px"}}>R</span><span id="price-starter" style={{fontFamily:"var(--fd)",fontSize:"48px",fontWeight:"800",letterSpacing:"-2px",lineHeight:"1"}}>{PRICES.starter[mode].toLocaleString()}</span><span style={{fontSize:"13px",color:"var(--muted)"}}>/mo</span></div>
        <div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"600",color:"var(--muted)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"8px"}}>Includes</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}><span className="badge b-vb">VeriBills</span></div></div>
        <div className="divider" style={{marginBottom:"20px"}}></div>
        <ul style={{listStyle:"none",display:"flex",flexDirection:"column",gap:"9px",marginBottom:"32px",flexGrow:"1"}}>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Up to R500K/month volume</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>2 user seats</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Email support (48h response)</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Basic analytics dashboard</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Sandbox environment</li>
        </ul>
        <Link className="btn btn-o btn-lg" style={{width:"100%",justifyContent:"center"}} href="/contact">Get started</Link>
      </div>
      <div className="conic-border" style={{borderRadius:"20px",padding:"36px 32px",display:"flex",flexDirection:"column",position:"relative",boxShadow:"0 20px 60px rgba(85,51,255,0.18)"}}>
        <div style={{position:"absolute",top:"-14px",left:"50%",transform:"translateX(-50%)",background:"var(--p)",color:"#fff",fontSize:"11px",fontWeight:"600",padding:"4px 16px",borderRadius:"100px",whiteSpace:"nowrap"}}>Most popular</div>
        <div style={{fontFamily:"var(--fd)",fontSize:"22px",fontWeight:"700",marginBottom:"4px"}}>Business</div>
        <div style={{fontSize:"13px",color:"var(--muted)",marginBottom:"28px"}}>For scaling organisations</div>
        <div style={{marginBottom:"28px"}}><span style={{fontFamily:"var(--fd)",fontSize:"13px",fontWeight:"600",color:"var(--muted)",verticalAlign:"top",lineHeight:"52px"}}>R</span><span id="price-business" style={{fontFamily:"var(--fd)",fontSize:"48px",fontWeight:"800",letterSpacing:"-2px",lineHeight:"1"}}>{PRICES.business[mode].toLocaleString()}</span><span style={{fontSize:"13px",color:"var(--muted)"}}>/mo</span></div>
        <div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"600",color:"var(--muted)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"8px"}}>Includes</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}><span className="badge b-vb">VeriBills</span><span className="badge b-morr">Morr ERP</span></div></div>
        <div className="divider" style={{marginBottom:"20px"}}></div>
        <ul style={{listStyle:"none",display:"flex",flexDirection:"column",gap:"9px",marginBottom:"32px",flexGrow:"1"}}>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Up to R5M/month volume</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>10 user seats</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Priority support (8h response)</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>SARS/SARB audit exports</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Dedicated account manager</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"var(--ink2)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"var(--pl)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="#5533FF" strokeWidth="1.8"></polyline></svg></span>Webhook &amp; event streaming</li>
        </ul>
        <Link className="btn btn-p btn-lg" style={{width:"100%",justifyContent:"center"}} href="/contact">Get started</Link>
      </div>
      <div style={{background:"var(--ink)",borderRadius:"20px",border:"1px solid rgba(255,255,255,0.08)",padding:"36px 32px",display:"flex",flexDirection:"column"}}>
        <div style={{fontFamily:"var(--fd)",fontSize:"22px",fontWeight:"700",color:"#fff",marginBottom:"4px"}}>Enterprise</div>
        <div style={{fontSize:"13px",color:"rgba(255,255,255,0.4)",marginBottom:"28px"}}>For complex operations</div>
        <div style={{marginBottom:"28px"}}><div style={{fontFamily:"var(--fd)",fontSize:"36px",fontWeight:"800",color:"#fff",lineHeight:"1",marginBottom:"4px"}}>Custom</div><div style={{fontSize:"13px",color:"rgba(255,255,255,0.4)"}}>Tailored to your scale</div></div>
        <div style={{marginBottom:"16px"}}><div style={{fontSize:"11px",fontWeight:"600",color:"rgba(255,255,255,0.35)",textTransform:"uppercase",letterSpacing:".8px",marginBottom:"8px"}}>Includes</div><div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}><span className="badge b-dark">VeriBills</span><span className="badge b-dark">Morr ERP</span></div></div>
        <div style={{height:"1px",background:"rgba(255,255,255,0.06)",marginBottom:"20px"}}></div>
        <ul style={{listStyle:"none",display:"flex",flexDirection:"column",gap:"9px",marginBottom:"32px",flexGrow:"1"}}>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="white" strokeWidth="1.8"></polyline></svg></span>Unlimited transaction volume</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="white" strokeWidth="1.8"></polyline></svg></span>Unlimited user seats</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="white" strokeWidth="1.8"></polyline></svg></span>Dedicated support (1h SLA)</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="white" strokeWidth="1.8"></polyline></svg></span>On-premise or private cloud</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="white" strokeWidth="1.8"></polyline></svg></span>SSO &amp; custom identity provider</li>
          <li style={{display:"flex",alignItems:"flex-start",gap:"10px",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:"1.5"}}><span style={{width:"18px",height:"18px",borderRadius:"50%",background:"rgba(255,255,255,0.1)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:"0",marginTop:"1px"}}><svg width="9" height="9" viewBox="0 0 10 10" fill="none"><polyline points="2,5 4,7 8,3" stroke="white" strokeWidth="1.8"></polyline></svg></span>Custom SLA &amp; uptime guarantee</li>
        </ul>
        <Link className="btn btn-w btn-lg" style={{width:"100%",justifyContent:"center"}} href="/contact">Contact sales</Link>
      </div>
    </div></div></section>
    <section className="section" style={{background:"var(--off)",paddingTop:"64px"}}><div className="inner-n">
      <p className="slabel" style={{textAlign:"center"}}>FAQ</p><h2 className="stitle" style={{textAlign:"center",marginBottom:"48px"}}>Common questions</h2>
      <details style={{borderBottom:"1px solid var(--border)",padding:"20px 0"}}><summary style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"600",cursor:"pointer",listStyle:"none",display:"flex",justifyContent:"space-between",alignItems:"center"}}>Can I start with one product and add more later?<svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="var(--muted)" strokeWidth="1.5"><path d="M4 6l4 4 4-4"></path></svg></summary><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",marginTop:"12px"}}>Each BIPRA product is available independently. Start with VeriBills and add Morr ERP when ready — no migration required. BipraPay can be layered in at any time on its own transaction-based pricing.</p></details>
      <details style={{borderBottom:"1px solid var(--border)",padding:"20px 0"}}><summary style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"600",cursor:"pointer",listStyle:"none",display:"flex",justifyContent:"space-between",alignItems:"center"}}>Is there a free trial?<svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="var(--muted)" strokeWidth="1.5"><path d="M4 6l4 4 4-4"></path></svg></summary><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",marginTop:"12px"}}>Yes — all plans include a 14-day free trial with full feature access. No credit card required to start.</p></details>
      <details style={{borderBottom:"1px solid var(--border)",padding:"20px 0"}}><summary style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"600",cursor:"pointer",listStyle:"none",display:"flex",justifyContent:"space-between",alignItems:"center"}}>What about BipraPay's fees?<svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="var(--muted)" strokeWidth="1.5"><path d="M4 6l4 4 4-4"></path></svg></summary><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",marginTop:"12px"}}>BipraPay isn't part of these subscription tiers — it's priced per transaction, by payment method and volume. See the full breakdown on the <Link href="/biprapay" style={{color:"var(--r)",fontWeight:"600"}}>BipraPay pricing page</Link>.</p></details>
      <details style={{padding:"20px 0"}}><summary style={{fontFamily:"var(--fd)",fontSize:"16px",fontWeight:"600",cursor:"pointer",listStyle:"none",display:"flex",justifyContent:"space-between",alignItems:"center"}}>Can we run BIPRA on our own infrastructure?<svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="var(--muted)" strokeWidth="1.5"><path d="M4 6l4 4 4-4"></path></svg></summary><p style={{fontSize:"14px",color:"var(--muted)",lineHeight:"1.75",marginTop:"12px"}}>Enterprise customers can opt for a private cloud or on-premise deployment. Talk to our sales team to discuss infrastructure requirements.</p></details>
    </div></section>

    <section className="section"><div className="inner">
      <p className="slabel" style={{textAlign:"center"}}>Compare plans</p>
      <h2 className="stitle" style={{textAlign:"center",maxWidth:"400px",margin:"0 auto 48px"}}>Feature comparison</h2>
      <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:"14px"}}>
        <thead><tr style={{borderBottom:"2px solid var(--border)"}}>
          <th style={{textAlign:"left",padding:"12px 16px",color:"var(--muted)",fontWeight:"500",width:"40%"}}>Feature</th>
          <th style={{textAlign:"center",padding:"12px 16px",color:"var(--ink)",fontWeight:"700"}}>Starter</th>
          <th style={{textAlign:"center",padding:"12px 16px",color:"var(--p)",fontWeight:"700"}}>Business</th>
          <th style={{textAlign:"center",padding:"12px 16px",color:"var(--ink)",fontWeight:"700"}}>Enterprise</th>
        </tr></thead>
        <tbody>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>Monthly volume</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>R500K</td><td style={{textAlign:"center",padding:"13px 16px",fontWeight:"600",color:"var(--p)"}}>R5M</td><td style={{textAlign:"center",padding:"13px 16px",fontWeight:"600"}}>Unlimited</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>User seats</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>2</td><td style={{textAlign:"center",padding:"13px 16px",fontWeight:"600",color:"var(--p)"}}>10</td><td style={{textAlign:"center",padding:"13px 16px",fontWeight:"600"}}>Unlimited</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>VeriBills (Bill presentment &amp; metering)</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>Morr ERP</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>API access</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>Standard</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--p)",fontWeight:"600"}}>Enhanced</td><td style={{textAlign:"center",padding:"13px 16px",fontWeight:"600"}}>Custom</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>Support SLA</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>Email 48h</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--p)",fontWeight:"600"}}>Priority 8h</td><td style={{textAlign:"center",padding:"13px 16px",fontWeight:"600"}}>Dedicated 1h</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>SARS/SARB exports</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>SSO / SAML</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td></tr>
          <tr style={{borderBottom:"1px solid var(--border)"}}><td style={{padding:"13px 16px",color:"var(--ink2)"}}>On-premise option</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td></tr>
          <tr><td style={{padding:"13px 16px",color:"var(--ink2)"}}>Dedicated account manager</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--muted)"}}>‒</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td><td style={{textAlign:"center",padding:"13px 16px",color:"var(--g)"}}>✓</td></tr>
        </tbody>
      </table></div>
    </div></section>
    </div>
  );
}
